debug: false

# List of game mode where the player is boosted on road blocks.
# Default: SURVIVAL, CREATIVE
enabled_gamemode:
  - SURVIVAL
  - CREATIVE

# Min y level so that road has an effect. Disable with -2147483648.
min_y: -2147483648
# Max y level so that road has an effect. Disable with 2147483647. Need to be > min_y
max_y: 2147483647

# Enable road speed boost when player is jumping or falling 1 block over the road.
speed_bonus_when_jumping: true

# Road blocks speed bonus per entity and per block.
# Values need to be > -1.0.
# 0 = default speed, 0.5 = 50% faster, -0.3 = 30% slower, 1.0 = 100% faster, 3.0 = 300% faster etc.
# PLAYER is a special value when there is no mounts. It can be removed if you don't want player to get any speed bonus.
speed_bonus:
  PLAYER:
    SUSPICIOUS_GRAVEL: 0.2
    GRAVEL: 0.1
    SAND: -0.1
    MUD: -0.2
  HORSE:
    SUSPICIOUS_GRAVEL: 0.5
    GRAVEL: 0.3
    SAND: -0.3
    MUD: -0.5
  CAMEL:
    SUSPICIOUS_SAND: 0.4
    SAND: 0.2
    MUD: -0.5

# Same as speed_bonus but inside town.
towny_speed_bonus:
  PLAYER:
    SUSPICIOUS_GRAVEL: 0.4
    GRAVEL: 0.1
    SAND: -0.1
    MUD: -0.2
  HORSE:
    SUSPICIOUS_GRAVEL: 0.6
    GRAVEL: 0.2
    SAND: -0.3
    MUD: -0.5
  CAMEL:
    SUSPICIOUS_SAND: 0.4
    SAND: 0.2
    MUD: -0.5

# Same as speed_bonus but in roads.
towny_roads_speed_bonus:
  PLAYER:
    SUSPICIOUS_GRAVEL: 0.4
    GRAVEL: 0.1
    SAND: -0.1
    MUD: -0.2
  HORSE:
    SUSPICIOUS_GRAVEL: 0.6
    GRAVEL: 0.2
    SAND: -0.3
    MUD: -0.5
  CAMEL:
    SUSPICIOUS_SAND: 0.4
    SAND: 0.2
    MUD: -0.5